/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package FrontEnd;

/**
 *
 * @author MSI TIN
 */
public class DlgRange extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgRange.class.getName());
    private String selectedRange; // <- valor elegido

    /**
     * Creates new form DlgRange
     */
    public DlgRange(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 90));
        jPanel2.setOpaque(true);
        jPanel3.setBackground(new java.awt.Color(17, 29, 74, 102)); // 102 = 0.4 * 255
        jPanel3.setOpaque(true);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 222, 255, 51), 1));
        setLocationRelativeTo(parent);
        setTitle("Select Range");

        JComboRange.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{
                    "--- Select a rol depending of your Range ---",
                    "1"
                }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        JComboRange = new javax.swing.JComboBox<>();
        DlgRange_Conf_Btn = new javax.swing.JButton();
        DlgRange_Can_Btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 398));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select your designated laboratory administrator range:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 470, 30));

        JComboRange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(JComboRange, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 470, -1));

        DlgRange_Conf_Btn.setBackground(new java.awt.Color(0, 0, 153));
        DlgRange_Conf_Btn.setForeground(new java.awt.Color(255, 255, 255));
        DlgRange_Conf_Btn.setText("Confirm");
        DlgRange_Conf_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DlgRange_Conf_BtnActionPerformed(evt);
            }
        });
        jPanel3.add(DlgRange_Conf_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 240, -1));

        DlgRange_Can_Btn.setBackground(new java.awt.Color(0, 0, 51));
        DlgRange_Can_Btn.setForeground(new java.awt.Color(255, 255, 255));
        DlgRange_Can_Btn.setText("Cancel");
        DlgRange_Can_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DlgRange_Can_BtnActionPerformed(evt);
            }
        });
        jPanel3.add(DlgRange_Can_Btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 240, -1));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 530, 170));
        jPanel3.getAccessibleContext().setAccessibleName("");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIGERL SYSTEM ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 50));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Laboratory Information Management");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 360, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EmergentsBg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DlgRange_Conf_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DlgRange_Conf_BtnActionPerformed
        selectedRange = JComboRange.getSelectedItem().toString();
        this.dispose();
    }//GEN-LAST:event_DlgRange_Conf_BtnActionPerformed

    private void DlgRange_Can_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DlgRange_Can_BtnActionPerformed
        selectedRange = null; // significa "cancelado"
        this.dispose();
    }//GEN-LAST:event_DlgRange_Can_BtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgRange dialog = new DlgRange(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DlgRange_Can_Btn;
    private javax.swing.JButton DlgRange_Conf_Btn;
    private javax.swing.JComboBox<String> JComboRange;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
