package FrontEnd;

import java.awt.Toolkit;
import java.awt.Image;


public class DlgRole extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DlgRole.class.getName());
    private String selectedRole; // <- valor elegido

    public DlgRole(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 90));
        jPanel2.setOpaque(true);
        jPanel3.setBackground(new java.awt.Color(17, 29, 74, 102)); // 102 = 0.4 * 255
        jPanel3.setOpaque(true);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 222, 255, 51), 1));
        setLocationRelativeTo(parent);
        setTitle("Select Role");

        JcomboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[]{
                    "--- Select a rol depending of your area ---",
                    "--- Research & Development ---",
                    "Research Assistant", "Research Scientist", "Laboratory Technician",
                    "Biochemist", "Microbiologist", "Molecular Biologist", "Geneticist",
                    "--- Quality & Control ---",
                    "Quality Control Analyst", "Quality Assurance Officer", "Validation Specialist", "QA/QC Technician",
                    "--- Technical & Support ---",
                    "Senior Lab Technician", "Maintenance Technician", "Safety Coordinator", "Instrumentation Technician",
                    "--- Management & Administration ---",
                    "Lab Manager", "Laboratory Supervisor", "Project Coordinator", "Operations Manager",
                    "--- Clinical / Environmental ---",
                    "Clinical Lab Technologist", "Pathology Assistant", "Environmental Analyst", "Hematology Technician",
                    "--- Specialized / Advanced ---",
                    "Bioinformatics Specialist", "Process Development Engineer", "Forensic Analyst", "Genetic Sequencing Specialist",
                     "--- Development---",
                     "FrontEnd",
                     "BackEnd",
                     "DB"
                }));
        // Renderer personalizado
        JcomboBoxRol.setRenderer(new javax.swing.plaf.basic.BasicComboBoxRenderer() {
            @Override
            public java.awt.Component getListCellRendererComponent(
                    javax.swing.JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {

                java.awt.Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                String text = (String) value;

                // Detectar encabezados (empiezan con ---)
                if (text.startsWith("---")) {
                    setFont(getFont().deriveFont(java.awt.Font.BOLD));
                    setForeground(java.awt.Color.LIGHT_GRAY);
                    setBackground(new java.awt.Color(30, 30, 30));
                    setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                } else {
                    setFont(getFont().deriveFont(java.awt.Font.PLAIN));
                    setForeground(java.awt.Color.WHITE);
                    setBackground(isSelected ? new java.awt.Color(0, 102, 204) : new java.awt.Color(17, 29, 74));
                    setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                }

                return c;
            }
        });

// Bloquear selección de encabezados
        JcomboBoxRol.addActionListener(e -> {
            String selected = (String) JcomboBoxRol.getSelectedItem();
            if (selected != null && selected.startsWith("---")) {
                // Evita mantener seleccionado el encabezado
                JcomboBoxRol.setSelectedIndex(-1);
            }
        });
    }

    public String getSelectedRole() {
        return selectedRole;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        JcomboBoxRol = new javax.swing.JComboBox<>();
        ConfirmDlgRol = new javax.swing.JButton();
        CancelDlgRol = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 398));
        setPreferredSize(new java.awt.Dimension(600, 398));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 0, -1, -1));

        jPanel2.setPreferredSize(new java.awt.Dimension(600, 390));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIGERL SYSTEM ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 50));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Laboratory Information Management");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 360, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Select your designated laboratory role:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 470, 30));

        JcomboBoxRol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        JcomboBoxRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JcomboBoxRolActionPerformed(evt);
            }
        });
        jPanel3.add(JcomboBoxRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 480, -1));

        ConfirmDlgRol.setBackground(new java.awt.Color(0, 0, 153));
        ConfirmDlgRol.setForeground(new java.awt.Color(255, 255, 255));
        ConfirmDlgRol.setText("Confirm");
        ConfirmDlgRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmDlgRolActionPerformed(evt);
            }
        });
        jPanel3.add(ConfirmDlgRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 220, 30));

        CancelDlgRol.setBackground(new java.awt.Color(0, 0, 51));
        CancelDlgRol.setForeground(new java.awt.Color(255, 255, 255));
        CancelDlgRol.setText("Cancel");
        CancelDlgRol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelDlgRolActionPerformed(evt);
            }
        });
        jPanel3.add(CancelDlgRol, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 250, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("© 2025 SIGERL System. All rights reserved.  Developed by Julian Felipe, Sara Álvarez & Carlos Vásquez");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, 20));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 530, 170));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 390));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/EmergentsBg.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConfirmDlgRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConfirmDlgRolActionPerformed
        selectedRole = JcomboBoxRol.getSelectedItem().toString();
        this.dispose();
    }//GEN-LAST:event_ConfirmDlgRolActionPerformed

    private void JcomboBoxRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JcomboBoxRolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JcomboBoxRolActionPerformed

    private void CancelDlgRolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelDlgRolActionPerformed
        selectedRole = null; // significa "cancelado"
        this.dispose();
    }//GEN-LAST:event_CancelDlgRolActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DlgRole dialog = new DlgRole(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelDlgRol;
    private javax.swing.JButton ConfirmDlgRol;
    private javax.swing.JComboBox<String> JcomboBoxRol;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
