package FrontEnd;

import java.awt.Color;
import java.awt.Font;
import java.awt.Toolkit;
import java.awt.Image;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingConstants;

public class FRMAdminDashboard extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRMAdminDashboard.class.getName());

    /**
     * Creates new form FRMAdminDashboard
     */
    public FRMAdminDashboard() {
        initComponents();

        // === Fondo general semitransparente ===
        jPanel2.setBackground(new Color(0, 0, 0, 90));
        jPanel2.setOpaque(true);

        // === Navbar estilo ===
        jPanelNavbar.setBackground(new Color(127, 222, 255, 90)); // azul clarito, semitransparente
        jPanelNavbar.setOpaque(true);
        jPanelNavbar.setBorder(
                javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new Color(255, 255, 255, 60))
        );

        // === Quick Actions Panel (Card Left) ===
        jPanelQuickActions.setBackground(new Color(127, 222, 255, 140));
        jPanelQuickActions.setOpaque(true);
        jPanelQuickActions.setBorder(
                javax.swing.BorderFactory.createLineBorder(new Color(255, 255, 255, 70), 1)
        );

        // === Recent Activity Panel (Card Right) ===
        jPanelRecentActivity.setBackground(new Color(127, 222, 255, 140));
        jPanelRecentActivity.setOpaque(true);
        jPanelRecentActivity.setBorder(
                javax.swing.BorderFactory.createLineBorder(new Color(255, 255, 255, 70), 1)
        );

        // === Recent Activity Panel (Card Right) ===
        jPanelEquipmentReservation.setBackground(new Color(127, 222, 255, 140));
        jPanelEquipmentReservation.setOpaque(true);
        jPanelEquipmentReservation.setBorder(
                javax.swing.BorderFactory.createLineBorder(new Color(255, 255, 255, 70), 1)
        );

        // === Inventory Management Panel (Card Rigth Down) ===
        jPanelInventoryManagement.setBackground(new Color(127, 222, 255, 140));
        jPanelInventoryManagement.setOpaque(true);
        jPanelInventoryManagement.setBorder(
                javax.swing.BorderFactory.createLineBorder(new Color(255, 255, 255, 70), 1)
        );

    }

    private void styleOutlineButton(javax.swing.JButton btn) {
        btn.setFocusPainted(false);
        btn.setContentAreaFilled(true);
        btn.setOpaque(true);

        btn.setBackground(new Color(255, 255, 255, 0)); // transparente
        btn.setForeground(new Color(60, 60, 60));      // texto gris oscuro
        btn.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(200, 200, 200))); // borde gris claro

        btn.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(245, 245, 245)); // gris claro al hover (#f5f5f5)
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn.setBackground(new Color(255, 255, 255, 0)); // transparente de nuevo
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanelNavbar = new javax.swing.JPanel();
        jPanelQuickActions = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButtonRegisterNewSample = new javax.swing.JButton();
        jButtonReserveEquipment = new javax.swing.JButton();
        jPanelRecentActivity = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelEquipmentReservation = new javax.swing.JPanel();
        jButtonReservationSystem = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanelInventoryManagement = new javax.swing.JPanel();
        jButtonInventoryManagement = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 700));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelNavbar.setBackground(new java.awt.Color(102, 255, 255));
        jPanel2.add(jPanelNavbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 80));

        jPanelQuickActions.setBackground(new java.awt.Color(0, 153, 153));
        jPanelQuickActions.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Quick Actions ");
        jPanelQuickActions.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jButtonRegisterNewSample.setBackground(new java.awt.Color(0, 102, 255));
        jButtonRegisterNewSample.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRegisterNewSample.setText("Register New Sample");
        jButtonRegisterNewSample.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterNewSampleActionPerformed(evt);
            }
        });
        jPanelQuickActions.add(jButtonRegisterNewSample, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 230, -1));

        jButtonReserveEquipment.setBackground(new java.awt.Color(0, 102, 255));
        jButtonReserveEquipment.setForeground(new java.awt.Color(255, 255, 255));
        jButtonReserveEquipment.setText("Reserve Equipment");
        jPanelQuickActions.add(jButtonReserveEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 230, -1));

        jPanel2.add(jPanelQuickActions, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 240, 320));

        jPanelRecentActivity.setBackground(new java.awt.Color(0, 153, 153));
        jPanelRecentActivity.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Recent Activity ");
        jPanelRecentActivity.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel2.add(jPanelRecentActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 650, 320));

        jPanelEquipmentReservation.setBackground(new java.awt.Color(0, 153, 153));
        jPanelEquipmentReservation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonReservationSystem.setForeground(new java.awt.Color(0, 0, 0));
        jButtonReservationSystem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clipboard-document-list.png"))); // NOI18N
        jButtonReservationSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReservationSystemActionPerformed(evt);
            }
        });
        jPanelEquipmentReservation.add(jButtonReservationSystem, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Reservations System");
        jPanelEquipmentReservation.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        jLabel5.setText("Schedule and manage equipment");
        jPanelEquipmentReservation.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 20));

        jLabel6.setText("usage");
        jPanelEquipmentReservation.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, -1));

        jPanel2.add(jPanelEquipmentReservation, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, 230, 150));

        jPanelInventoryManagement.setBackground(new java.awt.Color(0, 153, 153));
        jPanelInventoryManagement.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonInventoryManagement.setForeground(new java.awt.Color(0, 0, 0));
        jButtonInventoryManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/box.png"))); // NOI18N
        jButtonInventoryManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInventoryManagementActionPerformed(evt);
            }
        });
        jPanelInventoryManagement.add(jButtonInventoryManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Inventory Management");
        jPanelInventoryManagement.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, -1));

        jLabel8.setText("Track Reagents, Consumables and");
        jPanelInventoryManagement.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 180, 20));

        jLabel9.setText("supplies");
        jPanelInventoryManagement.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, -1));

        jPanel2.add(jPanelInventoryManagement, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 230, 150));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 690));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1000, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReservationSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReservationSystemActionPerformed
        FRMReservations frm = new FRMReservations();
        frm.setLocationRelativeTo(this); // centra respecto a la anterior
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonReservationSystemActionPerformed

    private void jButtonInventoryManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInventoryManagementActionPerformed
        FRMInventory frm = new FRMInventory();
        frm.setLocationRelativeTo(this); // centra respecto a la anterior
        frm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonInventoryManagementActionPerformed

    private void jButtonRegisterNewSampleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterNewSampleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegisterNewSampleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRMAdminDashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonInventoryManagement;
    private javax.swing.JButton jButtonRegisterNewSample;
    private javax.swing.JButton jButtonReservationSystem;
    private javax.swing.JButton jButtonReserveEquipment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelEquipmentReservation;
    private javax.swing.JPanel jPanelInventoryManagement;
    private javax.swing.JPanel jPanelNavbar;
    private javax.swing.JPanel jPanelQuickActions;
    private javax.swing.JPanel jPanelRecentActivity;
    // End of variables declaration//GEN-END:variables
}
