package FrontEnd;

import BackEnd.ClsMetEquipment;
import Connection.ClsConnection;
import java.sql.Connection;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Objects.ClsEquipment;

public class FRMAddEquipment extends javax.swing.JFrame {

    // Metodo constructor haciendo referencia a la tabla tblItems en frame FRMInventory para llenarla desde este frame
    private FRMInventory inventoryForm;

    public FRMAddEquipment(FRMInventory inventoryForm) {
        initComponents();
        this.inventoryForm = inventoryForm;

        ClsConnection CN;
        PreparedStatement PS;
        ResultSet RS;     
        setLocationRelativeTo(this);
        Errors();
        pnlNavigation.setVisible(false);
        CN = new ClsConnection();

        FillTable();

        // Cambio al JTextArea de la descripcion para que el texto baje solo
        txtDescription.setLineWrap(true);
        txtDescription.setWrapStyleWord(true);

        // Contador de caracteres maximos para la description: 
        final int MAX_CHAR = 200;

        lblCount.setText("Characters remaining: " + MAX_CHAR);

        // Metodo para obtener cuantos caracteres lleva escrito el usuario:
        txtDescription.getDocument().addDocumentListener(new javax.swing.event.DocumentListener() {

            private void updateCount() {
                int length = txtDescription.getText().length();
                int remaining = MAX_CHAR - length;

                lblCount.setText("Characters remaining: " + remaining);

                // Color warning when exceeding max
                if (remaining < 0) {
                    lblCount.setForeground(java.awt.Color.RED);
                } else {
                    lblCount.setForeground(java.awt.Color.BLACK);
                }
            }

            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                updateCount();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                updateCount();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                updateCount();
            }
        });

    }

    public void Errors() {
        lblErrorName.setVisible(false);
        lblErrorCategory.setVisible(false);
        lblErrorSupplier.setVisible(false);
        lblErrorLocation.setVisible(false);
        lblErrorStatus.setVisible(false);
        lblErrorQuantity.setVisible(false);
        lblErrorMinStock.setVisible(false);
    }

    public void Clear() {
        txtEquipmentName.setText("");
        txtEquipmentID.setText("");
        cboxEquipmentCategory.setSelectedIndex(0);
        txtEquipmentSupplier.setText("");
        txtEquipmentLocation.setText("");
        txtEquipmentStatus.setText("");
        numEquipmentQuantity.setValue(0);
        numEquipmentMinStock.setValue(0);
        txtDescription.setText("");
        Errors();
    }

    public void FillTable() {
        ClsMetEquipment Equipment = new ClsMetEquipment();
        inventoryForm.tblItems.setModel(Equipment.ListEquipment());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        pnlNavigation = new javax.swing.JPanel();
        btnNav4 = new javax.swing.JButton();
        btnNavDash = new javax.swing.JButton();
        btnNavReservations = new javax.swing.JButton();
        btnLogout = new javax.swing.JToggleButton();
        btnCerrar = new javax.swing.JButton();
        btnNavInventory = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnNav = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblEquipmentDescription = new javax.swing.JLabel();
        txtEquipmentName = new javax.swing.JTextField();
        lblEquipmentID = new javax.swing.JLabel();
        txtEquipmentID = new javax.swing.JTextField();
        lblEquipmentCategory = new javax.swing.JLabel();
        txtEquipmentSupplier = new javax.swing.JTextField();
        lblEquipmentSupplier = new javax.swing.JLabel();
        lblEquipmentQuantity = new javax.swing.JLabel();
        cboxEquipmentCategory = new javax.swing.JComboBox<>();
        numEquipmentQuantity = new javax.swing.JSpinner();
        lblEquipmentMinStock = new javax.swing.JLabel();
        numEquipmentMinStock = new javax.swing.JSpinner();
        lblEquipmentName = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        btnCancel = new javax.swing.JButton();
        btnAddToInventory = new javax.swing.JButton();
        txtEquipmentLocation = new javax.swing.JTextField();
        lblEquipmentLocation = new javax.swing.JLabel();
        txtEquipmentStatus = new javax.swing.JTextField();
        lblEquipmentStatus = new javax.swing.JLabel();
        lblErrorSupplier = new javax.swing.JLabel();
        lblErrorName = new javax.swing.JLabel();
        lblErrorCategory = new javax.swing.JLabel();
        lblErrorLocation = new javax.swing.JLabel();
        lblErrorStatus = new javax.swing.JLabel();
        lblErrorQuantity = new javax.swing.JLabel();
        lblErrorMinStock = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        lblCount = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBackground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.setForeground(new java.awt.Color(0, 0, 0));
        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1000, 666));
        jLayeredPane1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlNavigation.setBackground(new java.awt.Color(51, 255, 255));
        pnlNavigation.setPreferredSize(new java.awt.Dimension(250, 700));
        pnlNavigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNav4.setText("4");
        btnNav4.setToolTipText("");
        pnlNavigation.add(btnNav4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 210, 30));

        btnNavDash.setText("Dashboard");
        btnNavDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavDashActionPerformed(evt);
            }
        });
        pnlNavigation.add(btnNavDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 210, 30));

        btnNavReservations.setText("Reservations");
        btnNavReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavReservationsActionPerformed(evt);
            }
        });
        pnlNavigation.add(btnNavReservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, 30));

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlNavigation.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 543, 100, 40));

        btnCerrar.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrar.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setMaximumSize(new java.awt.Dimension(30, 30));
        btnCerrar.setMinimumSize(new java.awt.Dimension(30, 30));
        btnCerrar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        pnlNavigation.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 540, 40, 40));

        btnNavInventory.setText("Inventory");
        btnNavInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavInventoryActionPerformed(evt);
            }
        });
        pnlNavigation.add(btnNavInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 210, 30));

        jLayeredPane1.add(pnlNavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 10, 610));

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 50));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNav.setText("nav");
        btnNav.setPreferredSize(new java.awt.Dimension(25, 25));
        btnNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavActionPerformed(evt);
            }
        });
        jPanel2.add(btnNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Add New Item");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Add a new item to inventory");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLayeredPane1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTitle.setText("Item Information");
        jPanel1.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        lblEquipmentDescription.setText("Description");
        jPanel1.add(lblEquipmentDescription, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));
        jPanel1.add(txtEquipmentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 350, -1));

        lblEquipmentID.setText("Equipment ID");
        jPanel1.add(lblEquipmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 80, -1, -1));
        jPanel1.add(txtEquipmentID, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 300, -1));

        lblEquipmentCategory.setText("Equipment category");
        jPanel1.add(lblEquipmentCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));
        jPanel1.add(txtEquipmentSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, 350, -1));

        lblEquipmentSupplier.setText("Supplier");
        jPanel1.add(lblEquipmentSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, -1));

        lblEquipmentQuantity.setText("Quantity");
        jPanel1.add(lblEquipmentQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        cboxEquipmentCategory.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select category", "Item 2", "Item 3", "Item 4" }));
        cboxEquipmentCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxEquipmentCategoryActionPerformed(evt);
            }
        });
        jPanel1.add(cboxEquipmentCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 350, -1));
        jPanel1.add(numEquipmentQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 350, -1));

        lblEquipmentMinStock.setText("Minimum stock level");
        jPanel1.add(lblEquipmentMinStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));
        jPanel1.add(numEquipmentMinStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 310, 350, -1));

        lblEquipmentName.setText("Name of equipment");
        jPanel1.add(lblEquipmentName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 860, 100));

        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(150, 35));
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, -1, -1));

        btnAddToInventory.setText("Add to iventory");
        btnAddToInventory.setPreferredSize(new java.awt.Dimension(150, 35));
        btnAddToInventory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToInventoryActionPerformed(evt);
            }
        });
        jPanel1.add(btnAddToInventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));
        jPanel1.add(txtEquipmentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 350, -1));

        lblEquipmentLocation.setText("Location");
        jPanel1.add(lblEquipmentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));
        jPanel1.add(txtEquipmentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 350, -1));

        lblEquipmentStatus.setText("Status");
        jPanel1.add(lblEquipmentStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        lblErrorSupplier.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorSupplier.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblErrorSupplier.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorSupplier.setText("*");
        jPanel1.add(lblErrorSupplier, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 145, 10, -1));

        lblErrorName.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorName.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblErrorName.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorName.setText("*");
        jPanel1.add(lblErrorName, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 75, 10, -1));

        lblErrorCategory.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorCategory.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblErrorCategory.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorCategory.setText("*");
        jPanel1.add(lblErrorCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 145, 10, -1));

        lblErrorLocation.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorLocation.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblErrorLocation.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorLocation.setText("*");
        jPanel1.add(lblErrorLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(573, 215, 10, -1));

        lblErrorStatus.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorStatus.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblErrorStatus.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorStatus.setText("*");
        jPanel1.add(lblErrorStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 215, 10, -1));

        lblErrorQuantity.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorQuantity.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblErrorQuantity.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorQuantity.setText("*");
        jPanel1.add(lblErrorQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 285, 10, -1));

        lblErrorMinStock.setBackground(new java.awt.Color(255, 255, 255));
        lblErrorMinStock.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblErrorMinStock.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorMinStock.setText("*");
        jPanel1.add(lblErrorMinStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 285, 10, -1));

        btnSearch.setText("jButton1");
        jPanel1.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 100, 40, -1));

        btnClear.setText("Clear");
        btnClear.setPreferredSize(new java.awt.Dimension(150, 35));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        jPanel1.add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, -1, -1));

        lblCount.setText("Characters remaining: 200");
        jPanel1.add(lblCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, -1, -1));

        jLayeredPane1.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 920, 530));

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNavDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavDashActionPerformed
        FRMAdminDashboard Dashboard = new FRMAdminDashboard();
        Dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavDashActionPerformed

    private void btnNavReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavReservationsActionPerformed
        FRMReservations Reservations = new FRMReservations();
        Reservations.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavReservationsActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        FRMLogin Login = new FRMLogin();
        Login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnNavInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavInventoryActionPerformed
        FRMInventory Inventory = new FRMInventory();
        Inventory.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavInventoryActionPerformed

    private void btnNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavActionPerformed
        pnlNavigation.setVisible(!pnlNavigation.isVisible());
    }//GEN-LAST:event_btnNavActionPerformed

    private void btnAddToInventoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToInventoryActionPerformed

        String Name, Category, Supplier, Location, Status;
        int AddQuantity, MinStock;
        // boolean Availability;

        Name = txtEquipmentName.getText();
        Category = (String) cboxEquipmentCategory.getSelectedItem();
        Supplier = txtEquipmentSupplier.getText();
        Location = txtEquipmentLocation.getText();
        Status = txtEquipmentStatus.getText();
        AddQuantity = (int) numEquipmentQuantity.getValue();
        MinStock = (int) numEquipmentMinStock.getValue();

        if (!Name.isEmpty()) {
            if (!Category.isEmpty()) {
                if (!Supplier.isEmpty()) {
                    if (!Location.isEmpty()) {
                        if (!Status.isEmpty()) {
                            if (AddQuantity <= 0) {
                                if (MinStock <= 0) {

                                } else {
                                    lblErrorMinStock.setVisible(true);
                                }
                            } else {
                                lblErrorQuantity.setVisible(true);
                            }
                        } else {
                            lblErrorStatus.setVisible(true);
                        }
                    } else {
                        lblErrorLocation.setVisible(true);
                    }

                } else {
                    lblErrorSupplier.setVisible(true);
                }

            } else {
                lblErrorCategory.setVisible(true);
            }
        } else {
            lblErrorName.setVisible(true);
        }


    }//GEN-LAST:event_btnAddToInventoryActionPerformed

    private void cboxEquipmentCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxEquipmentCategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxEquipmentCategoryActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        Clear();
    }//GEN-LAST:event_btnClearActionPerformed

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRMAddEquipment.class.getName());

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToInventory;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnClear;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JButton btnNav;
    private javax.swing.JButton btnNav4;
    private javax.swing.JButton btnNavDash;
    private javax.swing.JButton btnNavInventory;
    private javax.swing.JButton btnNavReservations;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cboxEquipmentCategory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCount;
    private javax.swing.JLabel lblEquipmentCategory;
    private javax.swing.JLabel lblEquipmentDescription;
    private javax.swing.JLabel lblEquipmentID;
    private javax.swing.JLabel lblEquipmentLocation;
    private javax.swing.JLabel lblEquipmentMinStock;
    private javax.swing.JLabel lblEquipmentName;
    private javax.swing.JLabel lblEquipmentQuantity;
    private javax.swing.JLabel lblEquipmentStatus;
    private javax.swing.JLabel lblEquipmentSupplier;
    private javax.swing.JLabel lblErrorCategory;
    private javax.swing.JLabel lblErrorLocation;
    private javax.swing.JLabel lblErrorMinStock;
    private javax.swing.JLabel lblErrorName;
    private javax.swing.JLabel lblErrorQuantity;
    private javax.swing.JLabel lblErrorStatus;
    private javax.swing.JLabel lblErrorSupplier;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JSpinner numEquipmentMinStock;
    private javax.swing.JSpinner numEquipmentQuantity;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtEquipmentID;
    private javax.swing.JTextField txtEquipmentLocation;
    private javax.swing.JTextField txtEquipmentName;
    private javax.swing.JTextField txtEquipmentStatus;
    private javax.swing.JTextField txtEquipmentSupplier;
    // End of variables declaration//GEN-END:variables
}
