package FrontEnd;

import java.awt.Toolkit;
import java.awt.Image;
import Connection.ClsConnection;
import javax.swing.JOptionPane;
import java.sql.*;

// Import for logger
import java.util.logging.Logger;
import java.util.logging.Level;

public class FRMLogin extends javax.swing.JFrame {

    private static final Logger logger = Logger.getLogger(FRMLogin.class.getName());

    // This flag is used only for the current application run.
    // It is NOT persisted in the database.
    private static boolean firstLoginDone = false;

    /**
     * Creates new form FRMLogin
     */
    public FRMLogin() {
        initComponents();
        setLocationRelativeTo(null);

        // Semitransparent overlay panel
        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 90));
        jPanel2.setOpaque(true);

        // Login card style
        jPanel3.setBackground(new java.awt.Color(17, 29, 74, 102)); // 40% opacity
        jPanel3.setOpaque(true);
        jPanel3.setBorder(
                javax.swing.BorderFactory.createLineBorder(
                        new java.awt.Color(127, 222, 255, 51), 1
                )
        );

        // Set the default button so ENTER triggers Sign In
        getRootPane().setDefaultButton(Btn_login_sIn);
    }

    /**
     * Centralized login logic.
     * Called from the Sign In button and from ENTER key in password field.
     */
    private void doLogin() {
        String email = Txt_login_email.getText().trim();
        String pass = new String(Txt_login_pass.getPassword()).trim();

        // Basic validation
        if (email.isEmpty() || pass.isEmpty()) {
            JOptionPane.showMessageDialog(
                    this,
                    "Please fill in both email and password.",
                    "Missing data",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        // Call backend auth service
        BackEnd.ClsMetAuth auth = new BackEnd.ClsMetAuth();
        BackEnd.ClsMetAuth.LoginResult result = auth.login(email, pass);

        if (result == null) {
            // Either invalid credentials or internal error
            JOptionPane.showMessageDialog(
                    this,
                    "Invalid email or password.",
                    "Access denied",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        // Build full name for personalized messages
        String fullName = result.name + " " + result.lastName;
        String message;

        // First login message (for this app execution)
        if (!firstLoginDone) {
            if ("ADMIN".equals(result.accountType)) {
                message = "Welcome to SIGERL System Team, Admin " + fullName;
            } else {
                message = "Welcome to SIGERL System Service, " + fullName;
            }
        } else {
            // Regular welcome back message
            if ("ADMIN".equals(result.accountType)) {
                message = "Welcome back, Admin " + fullName;
            } else {
                message = "Welcome back, " + fullName;
            }
        }

        JOptionPane.showMessageDialog(
                this,
                message,
                "Login successful",
                JOptionPane.INFORMATION_MESSAGE
        );

        // Mark that at least one login was successful in the current session
        firstLoginDone = true;

        // Open proper dashboard based on account type
        if ("ADMIN".equals(result.accountType)) {
            // For now we keep the no-args constructor.
            // Later you can create an overloaded constructor to receive id/name.
            new FRMAdminDashboard().setVisible(true);
        } else {
            new FRMUserDashboard().setVisible(true);
        }

        // Close login window
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Txt_login_pass = new javax.swing.JPasswordField();
        Btn_login_login = new javax.swing.JButton();
        Btn_login_CA = new javax.swing.JButton();
        Btn_login_sIn = new javax.swing.JButton();
        Txt_login_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 666));
        setPreferredSize(new java.awt.Dimension(1000, 666));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIGERL SYSTEM ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 50, -1, 50));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Laboratory Information Management");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 360, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txt_login_pass.setBackground(new java.awt.Color(255, 255, 255));
        Txt_login_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_login_passActionPerformed(evt);
            }
        });
        jPanel3.add(Txt_login_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 360, -1));

        Btn_login_login.setBackground(new java.awt.Color(255, 255, 255));
        Btn_login_login.setForeground(new java.awt.Color(0, 0, 102));
        Btn_login_login.setText("Login");
        Btn_login_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Btn_login_login.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Btn_login_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_login_loginActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_login_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, -1));

        Btn_login_CA.setBackground(new java.awt.Color(255, 255, 255));
        Btn_login_CA.setForeground(new java.awt.Color(0, 51, 102));
        Btn_login_CA.setText("Create Account");
        Btn_login_CA.setToolTipText("");
        Btn_login_CA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Btn_login_CA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_login_CAActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_login_CA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 180, -1));

        Btn_login_sIn.setBackground(new java.awt.Color(0, 153, 255));
        Btn_login_sIn.setForeground(new java.awt.Color(255, 255, 255));
        Btn_login_sIn.setText("Sign In");
        Btn_login_sIn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Btn_login_sIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_login_sInActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_login_sIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 360, -1));

        Txt_login_email.setBackground(new java.awt.Color(255, 255, 255));
        Txt_login_email.setForeground(new java.awt.Color(30, 30, 30));
        Txt_login_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_login_emailActionPerformed(evt);
            }
        });
        jPanel3.add(Txt_login_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 360, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 230, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 240, 390, 220));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("© 2025 SIGERL System. All rights reserved.  Developed by Julian Felipe, Sara Álvarez & Carlos Vásquez");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 570, -1, 20));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background2.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 670));

        pack();
    }// </editor-fold>                        

    private void Txt_login_emailActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // Optional: move focus to password or trigger login
        Txt_login_pass.requestFocusInWindow();
    }                                               

    private void Btn_login_sInActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // Centralized login handler
        doLogin();
    }                                             

    private void Btn_login_CAActionPerformed(java.awt.event.ActionEvent evt) {                                             
        FRMCreateAccount frm = new FRMCreateAccount();
        frm.setLocationRelativeTo(this); // center relative to current window
        frm.setVisible(true);
        this.dispose();
    }                                            

    private void Btn_login_loginActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // This button is more like a tab style (Login tab).
        // For now it simply reloads the same form.
        this.dispose();
        new FRMLogin().setVisible(true);
    }                                               

    private void Txt_login_passActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // ENTER in password field will also trigger login
        doLogin();
    }                                              

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRMLogin().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton Btn_login_CA;
    private javax.swing.JButton Btn_login_login;
    private javax.swing.JButton Btn_login_sIn;
    private javax.swing.JTextField Txt_login_email;
    private javax.swing.JPasswordField Txt_login_pass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration                   
}
