/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FrontEnd;

/**
 *
 * @author MSI TIN
 */
public class FRMLogin extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRMLogin.class.getName());

    /**
     * Creates new form FRMLogin
     */
    public FRMLogin() {
        initComponents();
        jPanel2.setBackground(new java.awt.Color(0, 0, 0, 90));
        jPanel2.setOpaque(true);
        jPanel3.setBackground(new java.awt.Color(17, 29, 74, 102)); // 102 = 0.4 * 255
        jPanel3.setOpaque(true);
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(127, 222, 255, 51), 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        Txt_login_pass = new javax.swing.JPasswordField();
        Btn_login_login = new javax.swing.JButton();
        Btn_login_cA = new javax.swing.JButton();
        Btn_login_sIn = new javax.swing.JButton();
        Txt_login_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 0, -1, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("SIGERL SYSTEM ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, 50));

        jLabel3.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Laboratory Information Management");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 360, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txt_login_pass.setBackground(new java.awt.Color(255, 255, 255));
        Txt_login_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_login_passActionPerformed(evt);
            }
        });
        jPanel3.add(Txt_login_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 360, -1));

        Btn_login_login.setBackground(new java.awt.Color(255, 255, 255));
        Btn_login_login.setForeground(new java.awt.Color(0, 0, 102));
        Btn_login_login.setText("Login");
        Btn_login_login.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Btn_login_login.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        Btn_login_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_login_loginActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_login_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 190, -1));

        Btn_login_cA.setBackground(new java.awt.Color(255, 255, 255));
        Btn_login_cA.setForeground(new java.awt.Color(0, 51, 102));
        Btn_login_cA.setText("Create Account");
        Btn_login_cA.setToolTipText("");
        Btn_login_cA.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Btn_login_cA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_login_cAActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_login_cA, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 20, 180, -1));

        Btn_login_sIn.setBackground(new java.awt.Color(0, 153, 255));
        Btn_login_sIn.setForeground(new java.awt.Color(255, 255, 255));
        Btn_login_sIn.setText("Sign In");
        Btn_login_sIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_login_sInActionPerformed(evt);
            }
        });
        jPanel3.add(Btn_login_sIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 360, -1));

        Txt_login_email.setBackground(new java.awt.Color(255, 255, 255));
        Txt_login_email.setForeground(new java.awt.Color(30, 30, 30));
        Txt_login_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_login_emailActionPerformed(evt);
            }
        });
        jPanel3.add(Txt_login_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 360, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Email");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 230, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Password:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 230, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 390, 220));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("© 2025 SIGERL System. All rights reserved.  Developed by Julian Felipe, Sara Álvarez & Carlos Vásquez");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, -1, 20));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Usuario\\Documents\\NetBeansProjects\\SIGERL_System\\src\\main\\Resources\\Images\\BackGround.jpg")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_login_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_login_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_login_emailActionPerformed

    private void Btn_login_sInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_login_sInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_login_sInActionPerformed

    private void Btn_login_cAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_login_cAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_login_cAActionPerformed

    private void Btn_login_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_login_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_login_loginActionPerformed

    private void Txt_login_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_login_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_login_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRMLogin().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_login_cA;
    private javax.swing.JButton Btn_login_login;
    private javax.swing.JButton Btn_login_sIn;
    private javax.swing.JTextField Txt_login_email;
    private javax.swing.JPasswordField Txt_login_pass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables

}
