
package FrontEnd;

import java.awt.Toolkit;
import java.awt.Image;

public class FRMReservations extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FRMReservations.class.getName());

    /**
     * Creates new form FRMReservations
     */
    public FRMReservations() {
        initComponents();
        setLocationRelativeTo(this);
        pnlNavigation.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnNav = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnReserve = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        pnlNavigation = new javax.swing.JPanel();
        btnNav4 = new javax.swing.JButton();
        btnNavDash = new javax.swing.JButton();
        btnNav2 = new javax.swing.JButton();
        btnNav3 = new javax.swing.JButton();
        btnLogout = new javax.swing.JToggleButton();
        pnlStock = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtAvailable = new java.awt.TextField();
        pnlTotalItems1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtTotalEquipment = new java.awt.TextField();
        pnlCritical = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtUsed = new java.awt.TextField();
        pnlCategories = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtReservations = new java.awt.TextField();
        pnlReserve = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lblResDate = new javax.swing.JLabel();
        filterResEq = new javax.swing.JComboBox<>();
        lblResPurpose = new javax.swing.JLabel();
        lblResEq = new javax.swing.JLabel();
        lblResTime = new javax.swing.JLabel();
        txtPurpose = new javax.swing.JTextField();
        btnNewRes = new javax.swing.JButton();
        pnlReservations = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        filterCurrentRes = new javax.swing.JComboBox<>();
        pnlStatus = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSearchStatus = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(810, 540));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1000, 666));
        setResizable(false);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(1440, 900));
        jPanel1.setMinimumSize(new java.awt.Dimension(780, 600));
        jPanel1.setPreferredSize(new java.awt.Dimension(780, 910));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNav.setText("nav");
        btnNav.setPreferredSize(new java.awt.Dimension(25, 25));
        btnNav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavActionPerformed(evt);
            }
        });
        jPanel2.add(btnNav, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Equipment Reservations ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Schedule and manage equipment usage  ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        btnReserve.setText("(redundante?) New reservation");
        btnReserve.setPreferredSize(new java.awt.Dimension(100, 25));
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });
        jPanel2.add(btnReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 20, 120, -1));

        btnCerrar.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrar.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.setMaximumSize(new java.awt.Dimension(30, 30));
        btnCerrar.setMinimumSize(new java.awt.Dimension(30, 30));
        btnCerrar.setPreferredSize(new java.awt.Dimension(50, 50));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 40, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 60));

        pnlNavigation.setBackground(new java.awt.Color(51, 255, 255));
        pnlNavigation.setPreferredSize(new java.awt.Dimension(250, 910));
        pnlNavigation.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNav4.setText("4");
        btnNav4.setToolTipText("");
        pnlNavigation.add(btnNav4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 210, 30));

        btnNavDash.setText("Dashboard");
        btnNavDash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNavDashActionPerformed(evt);
            }
        });
        pnlNavigation.add(btnNavDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 210, 30));

        btnNav2.setText("2");
        pnlNavigation.add(btnNav2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 210, 30));

        btnNav3.setText("3");
        pnlNavigation.add(btnNav3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 210, 30));

        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlNavigation.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 100, 40));

        jPanel1.add(pnlNavigation, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        pnlStock.setPreferredSize(new java.awt.Dimension(185, 75));
        pnlStock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Available now");
        pnlStock.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtAvailable.setBackground(new java.awt.Color(60, 63, 65));
        txtAvailable.setEditable(false);
        txtAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAvailableActionPerformed(evt);
            }
        });
        pnlStock.add(txtAvailable, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, -1));

        jPanel1.add(pnlStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, 180, -1));

        pnlTotalItems1.setPreferredSize(new java.awt.Dimension(185, 75));
        pnlTotalItems1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setText("Total equipment");
        pnlTotalItems1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtTotalEquipment.setBackground(new java.awt.Color(60, 63, 65));
        txtTotalEquipment.setEditable(false);
        txtTotalEquipment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalEquipmentActionPerformed(evt);
            }
        });
        pnlTotalItems1.add(txtTotalEquipment, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, -1));

        jPanel1.add(pnlTotalItems1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 180, -1));

        pnlCritical.setPreferredSize(new java.awt.Dimension(185, 75));
        pnlCritical.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setText("In use");
        pnlCritical.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtUsed.setBackground(new java.awt.Color(60, 63, 65));
        txtUsed.setEditable(false);
        txtUsed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsedActionPerformed(evt);
            }
        });
        pnlCritical.add(txtUsed, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, -1));

        jPanel1.add(pnlCritical, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 70, 180, -1));

        pnlCategories.setPreferredSize(new java.awt.Dimension(185, 75));
        pnlCategories.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Today's bookings");
        pnlCategories.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txtReservations.setBackground(new java.awt.Color(60, 63, 65));
        txtReservations.setEditable(false);
        txtReservations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtReservationsActionPerformed(evt);
            }
        });
        pnlCategories.add(txtReservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, -1));

        jPanel1.add(pnlCategories, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 180, -1));

        pnlReserve.setMaximumSize(new java.awt.Dimension(470, 205));
        pnlReserve.setPreferredSize(new java.awt.Dimension(470, 200));
        pnlReserve.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Quick reserve");
        pnlReserve.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        lblResDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResDate.setText("Date");
        pnlReserve.add(lblResDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        filterResEq.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select equipment", "Item 2", "Item 3", "Item 4" }));
        filterResEq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterResEqActionPerformed(evt);
            }
        });
        pnlReserve.add(filterResEq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, -1));

        lblResPurpose.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResPurpose.setText("Purpose");
        pnlReserve.add(lblResPurpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        lblResEq.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResEq.setText("Equipment");
        pnlReserve.add(lblResEq, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        lblResTime.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblResTime.setText("Time slot");
        pnlReserve.add(lblResTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        pnlReserve.add(txtPurpose, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 160, -1));

        btnNewRes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnNewRes.setText("Reserve equipment");
        pnlReserve.add(btnNewRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 430, -1));

        jPanel1.add(pnlReserve, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        pnlReservations.setMaximumSize(new java.awt.Dimension(470, 205));
        pnlReservations.setPreferredSize(new java.awt.Dimension(470, 200));
        pnlReservations.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Current reservations");
        pnlReservations.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        pnlReservations.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, 440));

        filterCurrentRes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All status", "Active", "Confirmed", "Pending" }));
        pnlReservations.add(filterCurrentRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(362, 10, 100, -1));

        jPanel1.add(pnlReservations, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 370, -1, 490));

        pnlStatus.setPreferredSize(new java.awt.Dimension(270, 700));
        pnlStatus.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Equipment status");
        pnlStatus.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        txtSearchStatus.setBackground(new java.awt.Color(255, 255, 255));
        txtSearchStatus.setForeground(new java.awt.Color(153, 153, 153));
        txtSearchStatus.setText("Search equipment...");
        txtSearchStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchStatusActionPerformed(evt);
            }
        });
        pnlStatus.add(txtSearchStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 250, -1));

        jPanel1.add(pnlStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtReservationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtReservationsActionPerformed
        // TO DO: Display de cantidad de categrías (confirmar si hace falta o si puede ser reemplazado / borrado)
    }//GEN-LAST:event_txtReservationsActionPerformed

    private void txtUsedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsedActionPerformed
        // TO DO: Display de equipos en stock crítico
    }//GEN-LAST:event_txtUsedActionPerformed

    private void txtTotalEquipmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalEquipmentActionPerformed
        // TO DO: Display de la variable del total de equipos
    }//GEN-LAST:event_txtTotalEquipmentActionPerformed

    private void txtAvailableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAvailableActionPerformed
        // TO DO: Display de la variable de equipos en low stock
    }//GEN-LAST:event_txtAvailableActionPerformed

    private void btnNavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavActionPerformed
        pnlNavigation.setVisible(!pnlNavigation.isVisible());
    }//GEN-LAST:event_btnNavActionPerformed

    private void txtSearchStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchStatusActionPerformed
        // TO DO: Barra de búsqueda, a filtrar equipos para mostrar status
    }//GEN-LAST:event_txtSearchStatusActionPerformed

    private void filterResEqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterResEqActionPerformed
        // TO DO: Dropdown de lista de equipos. "Select equipment" podría equivaler a null para una validación de reserva
    }//GEN-LAST:event_filterResEqActionPerformed

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        // Este botón no es redundante?
    }//GEN-LAST:event_btnReserveActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void btnNavDashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNavDashActionPerformed
        FRMAdminDashboard Dashboard = new FRMAdminDashboard();
        Dashboard.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnNavDashActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        FRMLogin Login = new FRMLogin();
        Login.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FRMReservations().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JToggleButton btnLogout;
    private javax.swing.JButton btnNav;
    private javax.swing.JButton btnNav2;
    private javax.swing.JButton btnNav3;
    private javax.swing.JButton btnNav4;
    private javax.swing.JButton btnNavDash;
    private javax.swing.JButton btnNewRes;
    private javax.swing.JButton btnReserve;
    private javax.swing.JComboBox<String> filterCurrentRes;
    private javax.swing.JComboBox<String> filterResEq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblResDate;
    private javax.swing.JLabel lblResEq;
    private javax.swing.JLabel lblResPurpose;
    private javax.swing.JLabel lblResTime;
    private javax.swing.JPanel pnlCategories;
    private javax.swing.JPanel pnlCritical;
    private javax.swing.JPanel pnlNavigation;
    private javax.swing.JPanel pnlReservations;
    private javax.swing.JPanel pnlReserve;
    private javax.swing.JPanel pnlStatus;
    private javax.swing.JPanel pnlStock;
    private javax.swing.JPanel pnlTotalItems1;
    private java.awt.TextField txtAvailable;
    private javax.swing.JTextField txtPurpose;
    private java.awt.TextField txtReservations;
    private javax.swing.JTextField txtSearchStatus;
    private java.awt.TextField txtTotalEquipment;
    private java.awt.TextField txtUsed;
    // End of variables declaration//GEN-END:variables
}
